image_size:
  1: [210, 100]
  2: [100, 210]

balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 100
lr: 0.00001
transform: v1
models: ['h_cnn001_002_001_gap',
         'h_cnn001_002_002_gap',
         'h_cnn001_002_003_gap',
         'h_cnn001_002_004_gap',
         'h_cnn001_002_005_gap',
         'h_cnn001_002_007_gap',
         'h_cnn001_002_008_gap',
         'h_cnn001_002_009_gap',
         'h_cnn001_002_gap',
         'h_cnn001_003_001_gap',
         'h_cnn001_003_002_gap',
         'h_cnn001_003_003_gap',
         'h_cnn001_003_004_gap',
         'h_cnn001_003_gap',
         'h_cnn001_004_gap',
         'h_cnn001_gap',
         'h_cnn002_001_gap',
         'h_cnn002_002_gap',
         'h_cnn002_003_gap',
         'h_cnn002_004_gap',
         'h_cnn002_005_gap',
         'h_cnn002_006_gap',
         'h_cnn002_007_gap',
         'h_cnn002_008_gap',
         'h_cnn002_009_gap',
         'h_cnn002_gap',
         'h_cnn003_gap',
         'h_cnn004_gap',
         'h_cnnS_001_001_gap',
         'h_cnnS_001_002_gap',
         'h_cnnS_001_003_gap',
         'h_cnnS_001_004_gap',
         'h_cnnS_001_gap',
         'h_cnnS_002_001_gap',
         'h_cnnS_002_002_gap',
         'h_cnnS_002_003_gap',
         'h_cnnS_002_004_gap',
         'h_cnnS_002_gap',
         'h_cnnS_003_001_gap',
         'h_cnnS_003_002_gap',
         'h_cnnS_003_003_gap',
         'h_cnnS_003_004_gap',
         'h_cnnS_003_gap',
         'h_cnn_d_001_gap',
         'h_cnn_d_002_gap',
         'h_cnn_d_003',
         'h_cnn_d_003_gap',
         'k_cnn001_0013_gap',
         'k_cnn001_0014_gap',
         'k_cnn001_0015_gap',
         'k_cnn001_001_gap',
         'k_cnn001_002_gap',
         'k_cnn001_003_gap',
         'k_cnn001_004_gap',

         'k_cnn001_006_gap',
         'k_cnn001_007_gap',
         'k_cnn001_008_gap',
         'k_cnn001_009_gap',
         'k_cnn001_010_gap',
         'k_cnn001_011_gap',
         'k_cnn001_012_gap',
         'k_cnnS_001_001_gap',
         'k_cnnS_001_002_gap',
         'k_cnnS_001_003_gap',
         'k_cnnS_001_004_gap',
         'k_cnnS_001_005_gap',
         'k_cnnS_001_006_gap',
         'k_cnnS_001_007_gap',
         'k_cnnS_001_008_gap',
         'k_cnnS_001_009_gap',
         'k_cnnS_001_010_gap',
         'k_cnnS_001_gap',
         'k_cnnS_002_001_gap',
         'k_cnnS_002_002_gap',
         'k_cnnS_002_003_gap',
         'k_cnnS_002_004_gap',
         'k_cnnS_002_005_gap',
         'k_cnnS_002_gap',
         'k_cnnS_003_001_gap',
         'k_cnnS_003_002_gap',
         'k_cnnS_003_003_gap',
         'k_cnnS_003_004_gap',
         'k_cnnS_003_005_gap',
         'k_cnnS_003_gap',
         'k_cnnS_004_001_gap',
         'k_cnnS_004_002_gap',
         'k_cnnS_004_003_gap',
         'k_cnnS_004_004_gap',
         'k_cnnS_004_005_gap',
         'k_cnnS_004_gap']

loss: focal_loss
optimizer: adam
resampling_frequency: 8000