image_size:
  1: [210, 210]
  2: [140, 140]
  3: [100, 100]
  4: [200, 200]
balances: [False]
wav_chunks: [2]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svd
validation_db: voiced
batch_size_exp: 6
max_epochs: 150
lr: 0.00001
models: ["src.cnn.models.h_cnn002_001",
         "src.cnn.models.h_cnn002_002",
         "src.cnn.models.h_cnn002_003"]
loss: focal_loss
optimizer: adam