image_size:
  1: [220, 220]
  2: [230, 230]
  3: [240, 240]
  4: [250, 250]
balances: [False]
wav_chunks: [2]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svd
validation_db: voiced
batch_size_exp: 4
max_epochs: 150
lr: 0.00001
models: ["src.cnn.models.h_cnn002_009"]
loss: focal_loss
optimizer: adam