image_size:
  1: [100, 100]
  2: [80, 80]
balances: [False]
wav_chunks: [2, 3, 4]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svd
validation_db: voiced
batch_size_exp: 8
max_epochs: 100
lr: 0.00001
models: ["src.cnn.models.h_cnn003",
         "src.cnn.models.h_cnn004"]
loss: binary_crossentropy
optimizer: adam
