image_size:
  1: [100, 100]
  2: [80, 80]
balances: [False]
wav_chunks: [2]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svd
validation_db: voiced
batch_size_exp: 16
max_epochs: 50
lr: 0.00001
models: ["src.cnn.models.h_cnn002",
          "src.cnn.models.h_cnn001",
          "src.cnn.models.h_cnn001_001",
          "src.cnn.models.h_cnn001_002",
          "src.cnn.models.h_cnn001_003",
          "src.cnn.models.h_cnn001_004",
          "src.cnn.models.h_cnn001_005"]
loss: binary_crossentropy
optimizer: adam
