image_size:
  1: [200, 200]
  2: [140, 140]
  3: [100, 100]
balances: [False]
wav_chunks: [2, 3, 4]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svd
validation_db: voiced
batch_size_exp: 8
max_epochs: 300
lr: 0.00001
models: ["src.cnn.models.h_cnn001",
         "src.cnn.models.h_cnn001_001",
         "src.cnn.models.h_cnn001_002",
         "src.cnn.models.h_cnn001_003",
         "src.cnn.models.h_cnn001_004",
         "src.cnn.models.h_cnn001_005",
         "src.cnn.models.h_cnn002",
         "src.cnn.models.h_cnn003",
         "src.cnn.models.h_cnn004"]
loss: focal_loss
optimizer: adam
