image_size:
  1: [60, 240]
  3: [35, 350]
  5: [20, 500]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [1250]
fft_overlaps: [625]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 600
lr: 0.0001
transform: v1
models: [
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x11_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x6_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x10_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x12_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x5_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x7_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x4_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x11_001_dropout50_strides11_maxpool2x2_gap'
        ]
loss: focal_loss
optimizer: adam
focal_loss_gamma: 5