image_size:
  1: [220, 100]
  2: [230, 100]
  3: [240, 100]
  4: [250, 100]
  5: [210, 100]
  6: [200, 100]
  7: [100, 220]
  8: [100, 230]
  9: [100, 240]
  10: [100, 250]
  11: [100, 210]
  12: [100, 200]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 150
lr: 0.00001
transform: v1
models: ['h_cnnS_001.py',
 'h_cnnS_001_001.py',
 'h_cnnS_001_002.py',
 'h_cnnS_001_003.py',
 'h_cnnS_001_004.py',
 'h_cnnS_002.py',
 'h_cnnS_002_001.py',
 'h_cnnS_002_002.py',
 'h_cnnS_002_003.py',
 'h_cnnS_002_004.py',
 'h_cnnS_003.py',
 'h_cnnS_003_001.py',
 'h_cnnS_003_002.py',
 'h_cnnS_003_003.py',
 'h_cnnS_003_004.py']
loss: focal_loss
optimizer: adam