image_size:
  1: [100, 220]
  2: [100, 230]
  3: [100, 240]
  4: [100, 250]
  5: [100, 210]
  6: [100, 200]
  7: [220, 100]
  8: [230, 100]
  9: [240, 100]
  10: [250, 100]
  11: [210, 100]
  12: [200, 100]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 4
max_epochs: 150
lr: 0.00001
transform: v1
models: [
 'src.cnn.models.h_cnn001_002_006',
 'src.cnn.models.h_cnn001_005',
]
loss: focal_loss
optimizer: adam