image_size:
  1: [220, 220]
  2: [230, 230]
  3: [240, 240]
  4: [250, 250]
  5: [210, 210]
  6: [200, 200]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 4
max_epochs: 150
lr: 0.00001
transform: v1
models: ['src.cnn.models.h_cnn001',
 'src.cnn.models.h_cnn001_001',
 'src.cnn.models.h_cnn001_002',
 'src.cnn.models.h_cnn001_002_001',
 'src.cnn.models.h_cnn001_002_002',
 'src.cnn.models.h_cnn001_002_003',
 'src.cnn.models.h_cnn001_002_004',
 'src.cnn.models.h_cnn001_002_005',
 'src.cnn.models.h_cnn001_002_006',
 'src.cnn.models.h_cnn001_002_007',
]
loss: focal_loss
optimizer: adam