image_size:
  1: [220, 100]
  2: [230, 100]
  3: [240, 100]
  4: [250, 100]
  5: [210, 100]
  6: [200, 100]
  7: [100, 220]
  8: [100, 230]
  9: [100, 240]
  10: [100, 250]
  11: [100, 210]
  12: [100, 200]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 150
lr: 0.00001
transform: v1
models: ['src.cnn.models.h_cnn_d_001',
         'src.cnn.models.h_cnn_d_002',
         'src.cnn.models.h_cnn_d_003'
 ]
loss: focal_loss
optimizer: adam