image_size:
 1: [60, 240]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [1250]
fft_overlaps: [625]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 16
max_epochs: 10
lr: 0.0001
transform: v1
models: [
        'src.cnn.models.2conv_2x4_best.m3'
        ]
loss: focal_loss
optimizer: adam
focal_loss_gamma: 5
binary: 001
