image_size:
  1: [60, 240]
  2: [50, 300]
  3: [35, 350]
  4: [25, 400]
  5: [20, 500]
balances: [True]
wav_chunks: [1]
octaves: []
fft_lens: [2000]
fft_overlaps: [1000, 1600]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 600
lr: 0.0001
transform: v1
models: [
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x13_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x10_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x11_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x10_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x8_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x14_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x15_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x14_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x7_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x15_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x14_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x5_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x13_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x9_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x5_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x11_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x4_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x8_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x20_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x7_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x11_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x12_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x20_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x6_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x13_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x5_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x12_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x6_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x10_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x11_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x6_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x12_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x8_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x14_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x15_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x5_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x20_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x13_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x15_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x11_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x8_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x9_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x14_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x5_001_dropout50_strides11_maxpool2x2_gmp',
      'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x12_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x20_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x8_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x13_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x13_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x20_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x13_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x9_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x15_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x6_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x9_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x9_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x4_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x8_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x14_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x20_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x12_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x4_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x5_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x12_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x10_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x4_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x10_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x13_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x10_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x12_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x4_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x7_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x4_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x13_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x4_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x8_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x15_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x9_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x13_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x11_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x20_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x14_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x9_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x8_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x12_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x14_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x12_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x9_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x8_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x20_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x5_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x15_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x4_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x5_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x15_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x12_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x11_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x10_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x8_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x10_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x7_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x6_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x20_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x15_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x11_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x15_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x8_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x12_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x8_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x4_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x6_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x5_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x12_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x11_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x6_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x4_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x20_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x11_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x9_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x9_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x13_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x7_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x8_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x6_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x11_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x11_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x8_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x14_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x12_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x10_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x6_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x10_001_dropout00_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x8_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x10_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x20_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x12_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x11_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x7_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x13_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x7_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x12_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x12_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x10_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x11_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x5_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x15_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x6_001_dropout50_strides11_maxpool2x2_gap',
        'src.cnn.models.2conv_rectangular_3x.cnn_2conv3x13_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x15_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_2x.cnn_3conv2x15_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x15_001_dropout00_strides11_maxpool2x2',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x15_001_dropout00_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x7_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.2conv_rectangular_2x.cnn_2conv2x8_001_dropout50_strides11_maxpool2x2_gmp',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x6_001_dropout50_strides11_maxpool2x2',
        'src.cnn.models.3conv_rectangular_3x.cnn_3conv3x10_001_dropout50_strides11_maxpool2x2'
        ]
loss: focal_loss
optimizer: adam
focal_loss_gamma: 5