image_size:
  1: [220, 100]
  2: [230, 100]
  3: [240, 100]
  4: [250, 100]
  5: [210, 100]
  6: [200, 100]
  7: [100, 220]
  8: [100, 230]
  9: [100, 240]
  10: [100, 250]
  11: [100, 210]
  12: [100, 200]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 150
lr: 0.00001
transform: v1
models: ['src.cnn.models.k_cnnS_004',
 'src.cnn.models.k_cnnS_004_001',
 'src.cnn.models.k_cnnS_004_002',
 'src.cnn.models.k_cnnS_004_003',
 'src.cnn.models.k_cnnS_004_004',
 'src.cnn.models.k_cnnS_004_005',
 'src.cnn.models.h_cnnS_001',
 'src.cnn.models.k_cnnS_001_001',
 'src.cnn.models.k_cnnS_001_002',
 'src.cnn.models.k_cnnS_001_003',
 'src.cnn.models.k_cnnS_001_004',
 'src.cnn.models.k_cnnS_001_005',
 'src.cnn.models.k_cnnS_002',
 'src.cnn.models.k_cnnS_002_001',
 'src.cnn.models.k_cnnS_002_002',
 'src.cnn.models.k_cnnS_002_003',
 'src.cnn.models.k_cnnS_002_004',
 'src.cnn.models.k_cnnS_002_005',
 'src.cnn.models.k_cnnS_003',
 'src.cnn.models.k_cnnS_003_001',
 'src.cnn.models.k_cnnS_003_002',
 'src.cnn.models.k_cnnS_003_003',
 'src.cnn.models.k_cnnS_003_004',
 'src.cnn.models.k_cnnS_003_005',]
loss: focal_loss
optimizer: adam