stream:
- !!python/tuple
  - IP
  - dst: 10.1.12.1
    src: 192.168.1.2
balances: [False]
wav_chunks: [2]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svd
validation_db: voiced
batch_size_exp: 16
max_epochs: 50
lr: 0.00001
models: ["src.cnn.models.cnn002",
          "src.cnn.models.cnn001",
          "src.cnn.models.cnn001_001",
          "src.cnn.models.cnn001_002",
          "src.cnn.models.cnn001_003",
          "src.cnn.models.cnn001_004",
          "src.cnn.models.cnn001_005"]
loss: