image_size:
  1: [210, 100]
  2: [100, 210]

balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 200
lr: 0.00001
transform: v1
models: ['src.cnn.models.h_cnn001_002_001_gmp',
         'src.cnn.models.h_cnn001_002_002_gmp',
         'src.cnn.models.h_cnn001_002_003_gmp',
         'src.cnn.models.h_cnn001_002_004_gmp',
         'src.cnn.models.h_cnn001_002_005_gmp',
         'src.cnn.models.h_cnn001_002_007_gmp',
         'src.cnn.models.h_cnn001_002_008_gmp',
         'src.cnn.models.h_cnn001_002_009_gmp',
         'src.cnn.models.h_cnn001_002_gmp',
         'src.cnn.models.h_cnn001_003_001_gmp',
         'src.cnn.models.h_cnn001_003_002_gmp',
         'src.cnn.models.h_cnn001_003_003_gmp',
         'src.cnn.models.h_cnn001_003_004_gmp',
         'src.cnn.models.h_cnn001_003_gmp',
         'src.cnn.models.h_cnn001_004_gmp',
         'src.cnn.models.h_cnn001_gmp',
         'src.cnn.models.h_cnn002_001_gmp',
         'src.cnn.models.h_cnn002_002_gmp',
         'src.cnn.models.h_cnn002_003_gmp',
         'src.cnn.models.h_cnn002_004_gmp',
         'src.cnn.models.h_cnn002_005_gmp',
         'src.cnn.models.h_cnn002_006_gmp',
         'src.cnn.models.h_cnn002_007_gmp',
         'src.cnn.models.h_cnn002_008_gmp',
         'src.cnn.models.h_cnn002_009_gmp',
         'src.cnn.models.h_cnn002_gmp',
         'src.cnn.models.h_cnn003_gmp',
         'src.cnn.models.h_cnn004_gmp',
         'src.cnn.models.h_cnnS_001_001_gmp',
         'src.cnn.models.h_cnnS_001_002_gmp',
         'src.cnn.models.h_cnnS_001_003_gmp',
         'src.cnn.models.h_cnnS_001_004_gmp',
         'src.cnn.models.h_cnnS_001_gmp',
         'src.cnn.models.h_cnnS_002_001_gmp',
         'src.cnn.models.h_cnnS_002_002_gmp',
         'src.cnn.models.h_cnnS_002_003_gmp',
         'src.cnn.models.h_cnnS_002_004_gmp',
         'src.cnn.models.h_cnnS_002_gmp',
         'src.cnn.models.h_cnnS_003_001_gmp',
         'src.cnn.models.h_cnnS_003_002_gmp',
         'src.cnn.models.h_cnnS_003_003_gmp',
         'src.cnn.models.h_cnnS_003_004_gmp',
         'src.cnn.models.h_cnnS_003_gmp',
         'src.cnn.models.h_cnn_d_001_gmp',
         'src.cnn.models.h_cnn_d_002_gmp',
         'src.cnn.models.h_cnn_d_003',
         'src.cnn.models.h_cnn_d_003_gmp',
         'src.cnn.models.k_cnn001_0013_gmp',
         'src.cnn.models.k_cnn001_0014_gmp',
         'src.cnn.models.k_cnn001_0015_gmp',
         'src.cnn.models.k_cnn001_001_gmp',
         'src.cnn.models.k_cnn001_002_gmp',
         'src.cnn.models.k_cnn001_003_gmp',
         'src.cnn.models.k_cnn001_004_gmp',
         'src.cnn.models.k_cnn001_006_gmp',
         'src.cnn.models.k_cnn001_007_gmp',
         'src.cnn.models.k_cnn001_008_gmp',
         'src.cnn.models.k_cnn001_009_gmp',
         'src.cnn.models.k_cnn001_010_gmp',
         'src.cnn.models.k_cnn001_011_gmp',
         'src.cnn.models.k_cnn001_012_gmp',
         'src.cnn.models.k_cnnS_001_001_gmp',
         'src.cnn.models.k_cnnS_001_002_gmp',
         'src.cnn.models.k_cnnS_001_003_gmp',
         'src.cnn.models.k_cnnS_001_004_gmp',
         'src.cnn.models.k_cnnS_001_005_gmp',
         'src.cnn.models.k_cnnS_001_006_gmp',
         'src.cnn.models.k_cnnS_001_007_gmp',
         'src.cnn.models.k_cnnS_001_008_gmp',
         'src.cnn.models.k_cnnS_001_009_gmp',
         'src.cnn.models.k_cnnS_001_010_gmp',
         'src.cnn.models.k_cnnS_001_gmp',
         'src.cnn.models.k_cnnS_002_001_gmp',
         'src.cnn.models.k_cnnS_002_002_gmp',
         'src.cnn.models.k_cnnS_002_003_gmp',
         'src.cnn.models.k_cnnS_002_004_gmp',
         'src.cnn.models.k_cnnS_002_005_gmp',
         'src.cnn.models.k_cnnS_002_gmp',
         'src.cnn.models.k_cnnS_003_001_gmp',
         'src.cnn.models.k_cnnS_003_002_gmp',
         'src.cnn.models.k_cnnS_003_003_gmp',
         'src.cnn.models.k_cnnS_003_004_gmp',
         'src.cnn.models.k_cnnS_003_005_gmp',
         'src.cnn.models.k_cnnS_003_gmp',
         'src.cnn.models.k_cnnS_004_001_gmp',
         'src.cnn.models.k_cnnS_004_002_gmp',
         'src.cnn.models.k_cnnS_004_003_gmp',
         'src.cnn.models.k_cnnS_004_004_gmp',
         'src.cnn.models.k_cnnS_004_005_gmp',
         'src.cnn.models.k_cnnS_004_gmp']
loss: focal_loss
optimizer: adam
# resampling_frequency: 50000