image_size:
  1: [100, 210]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 300
lr: 0.00001
transform: v1
models: [
 'src.cnn.models.k_cnnS_001_004',]
loss: binary_crossentropy
optimizer: adam