image_size:
  1: [210, 210]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 4
max_epochs: 500
lr: 0.00001
transform: v1
models: [
 'src.cnn.models.k_cnn001_0013',
]
loss: focal_loss
optimizer: adam