image_size:
  1: [60, 240]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [1250]
fft_overlaps: [625]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 100
lr: 0.00001
transform: v1
models: [
         'src.cnn.models.h_cnn001_001_gmp',
         'src.cnn.models.h_cnn001_002_001_gap',
         'src.cnn.models.h_cnn001_002_001_gmp',
         'src.cnn.models.h_cnn001_002_002_gap',
         'src.cnn.models.h_cnn001_002_002_gmp',
         'src.cnn.models.h_cnn001_002_003_gap',
         'src.cnn.models.h_cnn001_002_003_gmp',
         'src.cnn.models.h_cnn001_002_004_gap',
         'src.cnn.models.h_cnn001_002_004_gmp',
         'src.cnn.models.h_cnn001_002_005_gap',
         'src.cnn.models.h_cnn001_002_005_gmp',
         'src.cnn.models.h_cnn001_002_006_gap',
         'src.cnn.models.h_cnn001_002_006_gmp',
         'src.cnn.models.h_cnn001_002_007_gap',
         'src.cnn.models.h_cnn001_002_007_gmp',
         'src.cnn.models.h_cnn001_002_008_gap',
         'src.cnn.models.h_cnn001_002_008_gmp',
         'src.cnn.models.h_cnn001_002_009_gap',
         'src.cnn.models.h_cnn001_002_009_gmp',
         'src.cnn.models.h_cnn001_002_gap',
         'src.cnn.models.h_cnn001_002_gmp',
         'src.cnn.models.h_cnn001_003_001_gap',
         'src.cnn.models.h_cnn001_003_001_gmp',
         'src.cnn.models.h_cnn001_003_002_gap',
         'src.cnn.models.h_cnn001_003_002_gmp',
         'src.cnn.models.h_cnn001_003_003_gap',
         'src.cnn.models.h_cnn001_003_003_gmp',
         'src.cnn.models.h_cnn001_003_004_gap',
         'src.cnn.models.h_cnn001_003_004_gmp',
         'src.cnn.models.h_cnn001_003_gap',
         'src.cnn.models.h_cnn001_003_gmp',
         'src.cnn.models.h_cnn001_004_gap',
         'src.cnn.models.h_cnn001_004_gmp',
         'src.cnn.models.h_cnn001_005_gap',
         'src.cnn.models.h_cnn001_005_gmp',
         'src.cnn.models.h_cnn001_gap',
         'src.cnn.models.h_cnn001_gmp',
         'src.cnn.models.h_cnn002_001_gap',
         'src.cnn.models.h_cnn002_001_gmp',
         'src.cnn.models.h_cnn002_002_gap',
         'src.cnn.models.h_cnn002_002_gmp',
         'src.cnn.models.h_cnn002_003_gap',
         'src.cnn.models.h_cnn002_003_gmp',
         'src.cnn.models.h_cnn002_004_gap',
         'src.cnn.models.h_cnn002_004_gmp',
         'src.cnn.models.h_cnn002_005_gap',
         'src.cnn.models.h_cnn002_005_gmp',
         'src.cnn.models.h_cnn002_006_gap',
         'src.cnn.models.h_cnn002_006_gmp',
         'src.cnn.models.h_cnn002_007_gap',
         'src.cnn.models.h_cnn002_007_gmp',
         'src.cnn.models.h_cnn002_008_gap',
         'src.cnn.models.h_cnn002_008_gmp',
         'src.cnn.models.h_cnn002_009_gap',
         'src.cnn.models.h_cnn002_009_gmp',
         'src.cnn.models.h_cnn002_gap',
         'src.cnn.models.h_cnn002_gmp',
         'src.cnn.models.h_cnn003_gap',
         'src.cnn.models.h_cnn003_gmp',
         'src.cnn.models.h_cnn004_gap',
         'src.cnn.models.h_cnn004_gmp',
         'src.cnn.models.h_cnnS_001_001_gap',
         'src.cnn.models.h_cnnS_001_001_gmp',
         'src.cnn.models.h_cnnS_001_002_gap',
         'src.cnn.models.h_cnnS_001_002_gmp',
         'src.cnn.models.h_cnnS_001_003_gap',
         'src.cnn.models.h_cnnS_001_003_gmp',
         'src.cnn.models.h_cnnS_001_004_gap',
         'src.cnn.models.h_cnnS_001_004_gmp',
         'src.cnn.models.h_cnnS_001_gap',
         'src.cnn.models.h_cnnS_001_gmp',
         'src.cnn.models.h_cnnS_002_001_gap',
         'src.cnn.models.h_cnnS_002_001_gmp',
         'src.cnn.models.h_cnnS_002_002_gap',
         'src.cnn.models.h_cnnS_002_002_gmp',
         'src.cnn.models.h_cnnS_002_003_gap',
         'src.cnn.models.h_cnnS_002_003_gmp',
         'src.cnn.models.h_cnnS_002_004_gap',
         'src.cnn.models.h_cnnS_002_004_gmp',
         'src.cnn.models.h_cnnS_002_gap',
         'src.cnn.models.h_cnnS_002_gmp',
         'src.cnn.models.h_cnnS_003_001_gap',
         'src.cnn.models.h_cnnS_003_001_gmp',
         'src.cnn.models.h_cnnS_003_002_gap',
         'src.cnn.models.h_cnnS_003_002_gmp',
         'src.cnn.models.h_cnnS_003_003_gap',
         'src.cnn.models.h_cnnS_003_003_gmp',
         'src.cnn.models.h_cnnS_003_004_gap',
         'src.cnn.models.h_cnnS_003_004_gmp',
         'src.cnn.models.h_cnnS_003_gap',
         'src.cnn.models.h_cnnS_003_gmp',
         'src.cnn.models.h_cnn_d_001_gap',
         'src.cnn.models.h_cnn_d_001_gmp',
         'src.cnn.models.h_cnn_d_002_gap',
         'src.cnn.models.h_cnn_d_002_gmp',
         'src.cnn.models.h_cnn_d_003',
         'src.cnn.models.h_cnn_d_003_gap',
         'src.cnn.models.h_cnn_d_003_gmp',
         'src.cnn.models.k_cnn001_0013_gap',
         'src.cnn.models.k_cnn001_0013_gmp',
         'src.cnn.models.k_cnn001_0014_gap',
         'src.cnn.models.k_cnn001_0014_gmp',
         'src.cnn.models.k_cnn001_0015_gap',
         'src.cnn.models.k_cnn001_0015_gmp',
         'src.cnn.models.k_cnn001_001_gap',
         'src.cnn.models.k_cnn001_001_gmp',
         'src.cnn.models.k_cnn001_002_gap',
         'src.cnn.models.k_cnn001_002_gmp',
         'src.cnn.models.k_cnn001_003_gap',
         'src.cnn.models.k_cnn001_003_gmp',
         'src.cnn.models.k_cnn001_004_gap',
         'src.cnn.models.k_cnn001_004_gmp',
         'src.cnn.models.k_cnn001_005_gap',
         'src.cnn.models.k_cnn001_005_gmp',
         'src.cnn.models.k_cnn001_006_gap',
         'src.cnn.models.k_cnn001_006_gmp',
         'src.cnn.models.k_cnnS_001_001_gap',
         'src.cnn.models.k_cnnS_001_001_gmp',
         'src.cnn.models.k_cnnS_001_002_gap',
         'src.cnn.models.k_cnnS_001_002_gmp',
         'src.cnn.models.k_cnnS_001_003_gap',
         'src.cnn.models.k_cnnS_001_003_gmp',
         'src.cnn.models.k_cnnS_001_004_gap',
         'src.cnn.models.k_cnnS_001_004_gmp',
         'src.cnn.models.k_cnnS_001_005_gap',
         'src.cnn.models.k_cnnS_001_005_gmp',
         'src.cnn.models.k_cnnS_001_006_gap',
         'src.cnn.models.k_cnnS_001_006_gmp',
         'src.cnn.models.k_cnnS_001_007_gap',
         'src.cnn.models.k_cnnS_001_007_gmp',
         'src.cnn.models.k_cnnS_001_008_gap',
         'src.cnn.models.k_cnnS_001_008_gmp',
         'src.cnn.models.k_cnnS_001_009_gap',
         'src.cnn.models.k_cnnS_001_009_gmp',
         'src.cnn.models.k_cnnS_001_010_gap',
         'src.cnn.models.k_cnnS_001_010_gmp',
         'src.cnn.models.k_cnnS_001_gap',
         'src.cnn.models.k_cnnS_001_gmp',
         'src.cnn.models.k_cnnS_002_001_gap',
         'src.cnn.models.k_cnnS_002_001_gmp',
         'src.cnn.models.k_cnnS_002_002_gap',
         'src.cnn.models.k_cnnS_002_002_gmp',
         'src.cnn.models.k_cnnS_002_003_gap',
         'src.cnn.models.k_cnnS_002_003_gmp',
         'src.cnn.models.k_cnnS_002_004_gap',
         'src.cnn.models.k_cnnS_002_004_gmp',
         'src.cnn.models.k_cnnS_002_005_gap',
         'src.cnn.models.k_cnnS_002_005_gmp',
         'src.cnn.models.k_cnnS_002_gap',
         'src.cnn.models.k_cnnS_002_gmp',
         'src.cnn.models.k_cnnS_003_001_gap',
         'src.cnn.models.k_cnnS_003_001_gmp',
         'src.cnn.models.k_cnnS_003_002_gap',
         'src.cnn.models.k_cnnS_003_002_gmp',
         'src.cnn.models.k_cnnS_003_003_gap',
         'src.cnn.models.k_cnnS_003_003_gmp',
         'src.cnn.models.k_cnnS_003_004_gap',
         'src.cnn.models.k_cnnS_003_004_gmp',
         'src.cnn.models.k_cnnS_003_005_gap',
         'src.cnn.models.k_cnnS_003_005_gmp',
         'src.cnn.models.k_cnnS_003_gap',
         'src.cnn.models.k_cnnS_003_gmp',
         'src.cnn.models.k_cnnS_004_001_gap',
         'src.cnn.models.k_cnnS_004_001_gmp',
         'src.cnn.models.k_cnnS_004_002_gap',
         'src.cnn.models.k_cnnS_004_002_gmp',
         'src.cnn.models.k_cnnS_004_003_gap',
         'src.cnn.models.k_cnnS_004_003_gmp',
         'src.cnn.models.k_cnnS_004_004_gap',
         'src.cnn.models.k_cnnS_004_004_gmp',
         'src.cnn.models.k_cnnS_004_005_gap',
         'src.cnn.models.k_cnnS_004_005_gmp',
         'src.cnn.models.k_cnnS_004_gap',
         'src.cnn.models.k_cnnS_004_gmp',
         'src.cnn.models.cnn_2conv3x3_001_dropout00_strides11_maxpool2x2',
         'src.cnn.models.cnn_2conv3x3_001_dropout00_strides11_maxpool2x2_global_avg',
         'src.cnn.models.cnn_2conv3x3_001_dropout05_strides11_maxpool2x2',
         'src.cnn.models.cnn_2conv3x3_001_dropout05_strides11_maxpool2x2_global_avg',
         'src.cnn.models.cnn_2conv3x3_002_dropout00_strides11_maxpool2x2',
         'src.cnn.models.cnn_2conv3x3_002_dropout00_strides11_maxpool2x2_global_avg',
         'src.cnn.models.cnn_2conv3x3_002_dropout50_strides11_maxpool2x2',
         'src.cnn.models.cnn_2conv3x3_002_dropout50_strides11_maxpool2x2_global_avg',
         'src.cnn.models.cnn_2conv3x3_003_dropout00_strides11_maxpool2x2',
         'src.cnn.models.cnn_2conv3x3_003_dropout00_strides11_maxpool2x2_global_avg',
         'src.cnn.models.cnn_2conv3x3_003_dropout50_strides11_maxpool2x2',
         'src.cnn.models.cnn_2conv3x3_003_dropout50_strides11_maxpool2x2_global_avg',
         'src.cnn.models.h_cnn001',
         'src.cnn.models.h_cnn001_001',
         'src.cnn.models.h_cnn001_002',
         'src.cnn.models.h_cnn001_002_001',
         'src.cnn.models.h_cnn001_002_002',
         'src.cnn.models.h_cnn001_002_003',
         'src.cnn.models.h_cnn001_002_004',
         'src.cnn.models.h_cnn001_002_005',
         'src.cnn.models.h_cnn001_002_006',
         'src.cnn.models.h_cnn001_002_007',
         'src.cnn.models.h_cnn001_002_008',
         'src.cnn.models.h_cnn001_002_009',
         'src.cnn.models.h_cnn001_003',
         'src.cnn.models.h_cnn001_003_001',
         'src.cnn.models.h_cnn001_003_002',
         'src.cnn.models.h_cnn001_003_003',
         'src.cnn.models.h_cnn001_003_004',
         'src.cnn.models.h_cnn001_004',
         'src.cnn.models.h_cnn001_005',
         'src.cnn.models.h_cnn002',
         'src.cnn.models.h_cnn002_001',
         'src.cnn.models.h_cnn002_002',
         'src.cnn.models.h_cnn002_003',
         'src.cnn.models.h_cnn002_004',
         'src.cnn.models.h_cnn002_005',
         'src.cnn.models.h_cnn002_006',
         'src.cnn.models.h_cnn002_007',
         'src.cnn.models.h_cnn002_008',
         'src.cnn.models.h_cnn002_009',
         'src.cnn.models.h_cnn003',
         'src.cnn.models.h_cnn004',
         'src.cnn.models.h_cnnS_001',
         'src.cnn.models.h_cnnS_001_001',
         'src.cnn.models.h_cnnS_001_002',
         'src.cnn.models.h_cnnS_001_003',
         'src.cnn.models.h_cnnS_001_004',
         'src.cnn.models.h_cnnS_002',
         'src.cnn.models.h_cnnS_002_001',
         'src.cnn.models.h_cnnS_002_002',
         'src.cnn.models.h_cnnS_002_003',
         'src.cnn.models.h_cnnS_002_004',
         'src.cnn.models.h_cnnS_003',
         'src.cnn.models.h_cnnS_003_001',
         'src.cnn.models.h_cnnS_003_002',
         'src.cnn.models.h_cnnS_003_003',
         'src.cnn.models.h_cnnS_003_004',
         'src.cnn.models.h_cnn_d_001',
         'src.cnn.models.h_cnn_d_002',
         'src.cnn.models.h_cnn_d_003',
         'src.cnn.models.k_cnn001_001',
         'src.cnn.models.k_cnn001_0013',
         'src.cnn.models.k_cnn001_0014',
         'src.cnn.models.k_cnn001_0015',
         'src.cnn.models.k_cnn001_002',
         'src.cnn.models.k_cnn001_003',
         'src.cnn.models.k_cnn001_004',
         'src.cnn.models.k_cnn001_005',
         'src.cnn.models.k_cnn001_006',
         'src.cnn.models.k_cnnS_001',
         'src.cnn.models.k_cnnS_001_001',
         'src.cnn.models.k_cnnS_001_002',
         'src.cnn.models.k_cnnS_001_003',
         'src.cnn.models.k_cnnS_001_004',
         'src.cnn.models.k_cnnS_001_005',
         'src.cnn.models.k_cnnS_001_006',
         'src.cnn.models.k_cnnS_001_007',
         'src.cnn.models.k_cnnS_001_008',
         'src.cnn.models.k_cnnS_001_009',
         'src.cnn.models.k_cnnS_001_010',
         'src.cnn.models.k_cnnS_002',
         'src.cnn.models.k_cnnS_002_001',
         'src.cnn.models.k_cnnS_002_002',
         'src.cnn.models.k_cnnS_002_003',
         'src.cnn.models.k_cnnS_002_004',
         'src.cnn.models.k_cnnS_002_005',
         'src.cnn.models.k_cnnS_003',
         'src.cnn.models.k_cnnS_003_001',
         'src.cnn.models.k_cnnS_003_002',
         'src.cnn.models.k_cnnS_003_003',
         'src.cnn.models.k_cnnS_003_004',
         'src.cnn.models.k_cnnS_003_005',
         'src.cnn.models.k_cnnS_004',
         'src.cnn.models.k_cnnS_004_001',
         'src.cnn.models.k_cnnS_004_002',
         'src.cnn.models.k_cnnS_004_003',
         'src.cnn.models.k_cnnS_004_004',
         'src.cnn.models.k_cnnS_004_005',
        ]
loss: focal_loss
optimizer: adam