image_size:
  1: [120, 480]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [1250]
fft_overlaps: [625]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 400
lr: 0.00001
transform: v1
models: [
         'src.cnn.models.h_cnn001_005_gap',
        ]
loss: focal_loss
optimizer: adam