image_size:
  1: [220, 100]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [256]
fft_overlaps: [128, 256, 512, 1024]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 500
lr: 0.00001
transform: v1
models: ['src.cnn.models.k_cnnS_003_001',
 'src.cnn.models.k_cnnS_001_003',
 'src.cnn.models.k_cnnS_004_002',
 'src.cnn.models.k_cnnS_002_003',
 'src.cnn.models.k_cnnS_001_001',
 'src.cnn.models.k_cnnS_002_002',
 'src.cnn.models.k_cnnS_003_002',
 'src.cnn.models.k_cnnS_003_004',
 'src.cnn.models.h_cnn003',
 'src.cnn.models.k_cnnS_004_004',]
loss: focal_loss
optimizer: adam