image_size:
  1: [60, 240]
balances: [False]
wav_chunks: [1]
octaves: []
fft_lens: [1250]
fft_overlaps: [625]
training_db: svdadult
validation_db: svdadult
batch_size_exp: 8
max_epochs: 500
lr: 0.01
transform: v1
models: ['src.cnn.models.laura_inspired.cnn_2conv2x7_001_dropout50_strides11_maxpool2x2']
loss: focal_loss
optimizer: adam